---
title: "Day x: TITLE"
author: "Celine Wuyts"
date: today
date-format: long
format: 
  pdf: 
    documentclass: scrreport
    execute: 
      echo: false
      warning: false
      error: false
  html:
    theme: 
      - flatly
      - styles.scss
    toc: true
    self-contained: TRUE
    code-fold: true
    code-tools: true
    execute: 
      echo: true
      warning: false
      error: false
---



```{r load_libraries}

library(tidyverse)

```

```{r get_labels, echo = FALSE}

labs <- knitr::all_labels()
labs_1 <- str_subset(labs, "^part_2-", negate = TRUE)
labs_2 <- str_subset(labs, "^part_1-", negate = TRUE)

labs_1 <- setdiff(labs_1, c("get_labels", "close_out"))
labs_2 <- setdiff(labs_2, c("get_labels", "close_out"))

```

```{r read_data, eval = FALSE}

dat_raw <- read.table("data/day_X_input.txt", header = FALSE, sep = "")

```

{{< pagebreak >}}

::: {.callout-tip}
## Attribution

This is a solution for [Advent of Code 2024, Day 1](https://adventofcode.com/2024/day/1).

:::

# Part 1


::: {.content-visible when-format="pdf"}

## R code

```{r ref.label=labs_1}
#| eval: false
#| echo: true
```

::: 

# Part 2

::: {.content-visible when-format="pdf"}

## R code

```{r ref.label=labs_2}
#| eval: false
#| echo: true
```

::: 



# Session information

```{r close_out}

sessionInfo()

```

